# Generated by Django 2.0.1 on 2018-01-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20180127_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='id',
        ),
        migrations.AddField(
            model_name='room',
            name='display_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
